[package]
name = "peridot-counter-ctx"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
peridot = { workspace = true }
wiggle = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }
log = { workspace = true }
