[package]
name = "peridot-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "29.0.1"
wasi-common = "29.0.1"
peridot = { path = "crates/peridot" }
peridot-token-ctx = { path = "crates/peridot-token-ctx", optional = true }
peridot-geds-ctx = { path = "crates/peridot-geds-ctx", optional = true }
peridot-clock-ctx = { path = "crates/peridot-clock-ctx", optional = true }
nix = { version = "0.29.0", features = ["process"] }
peridot-overseer-grpc = { path = "crates/peridot-overseer-grpc" }
env_logger = "0.11.6"
log = "0.4.26"
clap = { version = "4.5.31", features = ["derive"] }
