[package]
name = "peridot-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository = "https://github.com/pablogs98/Peridot"

[workspace]
members = [
    "crates/containerd-shim-peridot",
    "crates/contexts/imagenet-preprocessing",
    "crates/peridot",
    "crates/contexts/peridot-clock-ctx",
    "crates/contexts/peridot-geds-ctx",
    "crates/peridot-overseer",
    "crates/peridot-overseer-grpc",
    "crates/contexts/peridot-s3-ctx",
    "crates/contexts/peridot-batch-ctx",
    "crates/contexts/peridot-syscall-batching-ctx",
    "crates/contexts/peridot-token-ctx",
    "crates/contexts/peridot-counter-ctx"
]

[workspace.package]
version = "0.1.0"
authors = ["Pablo Gimeno Sarroca", "Miquel Álvarez Ruiz"]
edition = "2021"

[[bin]]
name = "peridot"
path = "src/main.rs"

[workspace.dependencies]
peridot = { path = "crates/peridot", version = "0.1.0" }
peridot-overseer-grpc = { path = "crates/peridot-overseer-grpc" , version = "0.1.0" }

clap = { version = "4.5.31", features = ["derive"] }
log = "0.4.26"
env_logger = "0.11.6"
wasmtime = "38.0.3"
wasmtime-wasi = "38.0.3"
tokio = { version = "1", features = ["full"] }
tonic = "0.12.3"
aws-sdk-s3 = "1.79.0"
aws-config = "1.1.7"

# for context crates
wiggle = "38.0.3"
anyhow = "1.0.95"
async-trait = "0.1.85"

[dependencies]
nix = { version = "0.29.0", features = ["process"] }
peridot-token-ctx = { path = "crates/contexts/peridot-token-ctx", optional = true }
peridot-geds-ctx = { path = "crates/contexts/peridot-geds-ctx", optional = true }
peridot-clock-ctx = { path = "crates/contexts/peridot-clock-ctx", optional = true }
peridot-s3-ctx = { path = "crates/contexts/peridot-s3-ctx", optional = true }
peridot-counter-ctx = { path = "crates/contexts/peridot-counter-ctx", optional = true }
wasmtime-wasi = { workspace = true }

wasmtime = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
peridot = { workspace = true }
tokio = { version = "1.48.0", features = ["rt", "rt-multi-thread", "macros"] }

[features]
token = ["dep:peridot-token-ctx"]
s3 = ["dep:peridot-s3-ctx"]
geds = ["dep:peridot-geds-ctx"]
clock = ["dep:peridot-clock-ctx"]
counter = ["dep:peridot-counter-ctx"]
