[package]
name = "containerd-shim-peridot"
version.workspace = true
authors.workspace = true
edition.workspace = true

[patch.crates-io]
oci-spec = "0.8.3"


[dependencies.containerd-shim-wasm]
git = "https://github.com/miqalvarez/runwasi"

[dependencies]
wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
peridot = { workspace = true }
peridot-token-ctx = {path = "../contexts/peridot-token-ctx", optional = true}
walkdir = "2.5.0"

[features]
token = ["dep:peridot-token-ctx"]

[[bin]]
name = "containerd-shim-peridot-v1"
path = "src/main.rs"
