[package]
name = "containerd-shim-peridot"
version.workspace = true
authors.workspace = true
edition.workspace = true

[patch.crates-io]
oci-spec = "0.8.3"

[dependencies.containerd-shim-wasm]
git = "https://github.com/miqalvarez/runwasi"

[dependencies]
wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
peridot = { workspace = true }
peridot-token-ctx = {path = "../contexts/peridot-token-ctx"}
peridot-counter-ctx = {path = "../contexts/peridot-counter-ctx"}
peridot-clock-ctx = {path = "../contexts/peridot-clock-ctx"}
peridot-s3-ctx = {path = "../contexts/peridot-s3-ctx"}
peridot-batch-ctx = {path = "../contexts/peridot-batch-ctx"}
peridot-syscall-batching-ctx = {path = "../contexts/peridot-syscall-batching-ctx"}
oci-spec = "0.8.3"
env_logger = "0.11.8"


[[bin]]
name = "containerd-shim-peridot-v1"
path = "src/main.rs"