[package]
name = "peridot-batch-ctx"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
uuid = { version = "1.18.1", features = ["v4"] }
arrow = "50.0.0"
parquet = "50.0.0"
chrono = "=0.4.31"

peridot = { workspace = true }
wasmtime-wasi = { workspace = true }
wiggle = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
wasmtime = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
aws-sdk-s3 = {workspace = true}
aws-config = { workspace = true, features = ["behavior-version-latest"] }
serde = { version = "1.0.217", features = ["derive"] }

[dev-dependencies]
bytes = "1"
