cmake_minimum_required(VERSION 3.29)
project(wasm)
set(CMAKE_CXX_STANDARD 26)
set(CMAKE_C_STANDARD 23)
add_subdirectory(helloworld)
add_subdirectory(logsystem)
add_subdirectory(read_write)
add_subdirectory(sqlite)
add_subdirectory(hostcall_latency)
add_subdirectory(io_writer)
add_subdirectory(iops)
add_subdirectory(write_1g)