[package]
name = "peridot-batch-ctx"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
wiggle = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
wasi-common = { workspace = true }
wasmtime = { workspace = true }
log = { workspace = true }
aws-sdk-s3 = "1.79.0"
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
tokio = { workspace = true }
rand = "0.8.5"
arrow = "50.0.0"
parquet = "50.0.0"
chrono = "=0.4.31"