[package]
name = "peridot-overseer-grpc"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
tokio-macros = "2.5.0"
tower = "0.5.2"
hyper-util = "0.1.10"
prost = "0.13.5"
prost-types = "0.13.5"
tokio = { workspace = true , features = ["full"] }
log = { workspace = true }
tonic = { workspace = true }

[build-dependencies]
tonic-build = "0.12.3"
prost-build = "0.13.5"