[package]
name = "peridot"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
wiggle = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
wasi-common = { workspace = true }
wasmtime = { workspace = true }
log = { workspace = true }
serde = { version = "1.0.217", features = ["derive"] }
log = { workspace = true }
uuid = { version = "1.18.1", features = ["v4"] }
peridot-overseer-grpc = { workspace = true }
serde_yaml = "0.9.34+deprecated"