[package]
name = "peridot"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_yaml = "0.9.34"
log = { workspace = true }
uuid = { version = "1.18.1", features = ["v4"] }
peridot-overseer-grpc = { workspace = true }
