syntax = "proto3";

package overseer;

service Overseer {
  rpc RegisterModule (RegisterModuleRequest) returns (ModuleResponse);
  rpc RemoveModule (RemoveModuleRequest) returns (ModuleResponse);
  rpc UpdateMaxBandwidth (UpdateMaxBandwidthRequest) returns (UpdateMaxBandwidthResponse);
}

message RegisterModuleRequest {
  uint32 pid = 1;
  double demand = 2;
}

message RemoveModuleRequest {
  uint32 pid = 1;
}

message UpdateMaxBandwidthRequest {
  repeated uint32 pids = 1;
}

message UpdateMaxBandwidthResponse {
  map<uint32, double> stats = 1;
}

message ModuleResponse {

}