syntax = "proto3";

package overseer;

service Overseer {
  rpc RegisterModule (RegisterModuleRequest) returns (ModuleResponse);
  rpc RemoveModule (RemoveModuleRequest) returns (ModuleResponse);
  rpc UpdateMaxBandwidth (UpdateIoStatsRequest) returns (UpdateIoStatsResponse);
}

message RegisterModuleRequest {
  uint32 pid = 1;
  string name = 2;
}

message RemoveModuleRequest {
  uint32 pid = 1;
}

message UpdateIoStatsRequest {
  repeated uint32 pids = 1;
}

message UpdateIoStatsResponse {
  map<uint32, int32> stats = 1;
}

message ModuleResponse {

}